# Generated by Django 5.2.7 on 2025-11-03 12:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del país', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglas', models.CharField(help_text='Siglas de la posición ej:( POR ,DFC, LTI, ...)', max_length=3, unique=True)),
                ('significado', models.CharField(help_text='Nombre completo de la posición ej: Defensa Central', max_length=140)),
                ('tipo', models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('CEN', 'Centrocampista'), ('DEL', 'Delantero')], help_text='El tipo de posición en el campo', max_length=3)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción más detallada de la posición y sus funciones.', null=True)),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del jugador', max_length=100)),
                ('equipo', models.CharField(help_text='Equipo real del jugador', max_length=100)),
                ('pac', models.IntegerField(default=1, help_text='Velocidad del jugador', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('sho', models.IntegerField(default=1, help_text='Disparo del jugador', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('pas', models.IntegerField(default=1, help_text='Pase del jugador', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('dri', models.IntegerField(default=1, help_text='Regate del jugador', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('defe', models.IntegerField(default=1, help_text='Defensa del jugador', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('phy', models.IntegerField(default=1, help_text='Físico del jugador', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('nacionalidad', models.ForeignKey(help_text='Nacionalidad del jugador', on_delete=django.db.models.deletion.PROTECT, to='ultimate_team_app.nacionalidad')),
                ('posicion_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ultimate_team_app.posicion')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nick', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ManyToManyField(to='ultimate_team_app.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del equipo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción más detallada del equipo.', null=True)),
                ('jugadores', models.ManyToManyField(blank=True, help_text='Jugadores del equipo', related_name='equipos', to='ultimate_team_app.jugador')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimate_team_app.usuario')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
