# Generated by Django 5.2.7 on 2025-11-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimate_team_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={'verbose_name': 'Nacionalidad', 'verbose_name_plural': 'Nacionalidades'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AddField(
            model_name='jugador',
            name='desactivado',
            field=models.BooleanField(default=False),
        ),
    ]
