# Generated by Django 5.2.7 on 2025-11-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimate_team_app', '0002_alter_nacionalidad_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='valoracion_media',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
